apiVersion: pulumi.com/v1
kind: Program
metadata:
  name: pu-program-{{ .Values.stage }}-{{ .Values.region }}
program:
  resources:
    do_project:
      properties:
        description: A project to represent test resources via Pulumi
        environment: development2
        name: pu-{{ .Values.stage }}-{{ .Values.region }}
      type: digitalocean:Project
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: pu-stack-{{ .Values.stage }}-{{ .Values.region }}
spec:
  destroyOnFinalize: true
  envRefs:
    DIGITALOCEAN_TOKEN:
      env:
        name: DIGITALOCEAN_TOKEN
      type: Env
  programRef:
    name: pu-program-{{ .Values.stage }}-{{ .Values.region }}
  stack: ediri/pu-program-{{ .Values.stage }}-{{ .Values.region }}/{{ .Values.stage }}
