apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cd-summit-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat-a
      - stage: uat-b
      - stage: prod
  template:
    metadata:
      name: cd-summit-demo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: cd-summit-demo:{{stage}}
    spec:
      project: default
      sources:
      - repoURL: https://github.com/dirien/kargo-test
        targetRevision: main
        path: stages/{{stage}}
        helm:
          valueFiles:
          - $values/stages/{{stage}}/values.yaml
      - repoURL: https://github.com/dirien/kargo-test
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
